### ISSUE TITLE
Separate DCC integrations (plugins) from the core

### ISSUE THREAD

**Issue by BigRoy** [fabric-engine/Kraken#335]
## Goal

Ensure no DCC specific code is contained within the core of the Kraken code. Kraken should be able to "run" even without any knowledge of any DCC being present, as such simplifying the core.

## Description

Looking over the code base of Kraken I found something that struck me as a bit odd. The `core/kraken_system.py` contains code specific to the DCCs like Maya and Softimage. Specifically the code in the `loadCoreClient()` method. It's still relatively small, but I guess it's a good time as any to bring it up.

I can imagine that this becomes more of a problem as the range of supported DCCs grows. Theoretically I'd imagine additional plug-ins to "register" themselves and that each plug-in defines the name of the Host (e.g. Maya or Softimage) and that it contains the correct method to create the Fabric Engine client.

I'd imagine nothing of the core would actually contain DCC specific content and wouldn't require any of the plugins to be registered. Theoretically the plug-ins could become their own separate repository down the line where others like `kraken-modo` and `kraken-max` could exist alongside `kraken-maya`.

**Comment by EricTRocks** [comment]
Hey @BigRoy 

This is in place because there needs to be a way to get the host application somehow. We're testing if DCC specific modules are available, if not, it moves to the next, and so on. If it never finds one it defaults back to Python being the "host".

We could abstract these calls into the individual dcc plugin modules and implement a getClient() method that would be called such as:

```
from kraken import plugins

# Then in the Kraken System class
self.client = plugins.getClient()
```

With each additional DCC that has Fabric and Python available we'll be adding support. I wouldn't think that each plug-in should be its own repo but that people can fork Kraken and / modify plug-ins and submit pull requests back that we will merge in. That said, nothing stopping someone from creating their own repo with a Kraken plug-in in it. However We're going to build our own and keep them within the main repo. The plug-ins are so light weight that it really doesn't make sense to spin them off on their own.

**Comment by BigRoy** [comment]
> We could abstract these calls into the individual dcc plugin modules and implement a getClient() method that would be called such as:

Sure. Something like that. It would act more like a plug-in manager where it would look for plug-ins in a `KRAKEN_PLUGIN_PATHS` or alike and they get registered with Kraken. And by default it's local plugins folder gets searched (or added to that path?)

You would be able to do something like:

```python
import kraken.plugins

for plugin in kraken.plugins.getRegisteredPlugins():
    if plugin.isCurrentHost():
        client = plugin.getClient()
        break
else:
    client = "standalone" ?
```

> With each additional DCC that has Fabric and Python available we'll be adding support. I wouldn't think that each plug-in should be its own repo but that people can fork Kraken and / modify plug-ins and submit pull requests back that we will merge in. That said, nothing stopping someone from creating their own repo with a Kraken plug-in in it. However We're going to build our own and keep them within the main repo. The plug-ins are so light weight that it really doesn't make sense to spin them off on their own.

Sure. Not saying it's the best way to go. I do have to be honest and say that I feel *kraken* feels quite big just because there's just so many folders. Even though the lines of code I think isn't in the very high numbers it feels like a large package. Hasn't been an issue for me, but I can see it grow and grow.

Separating more will also make it harder to keep "versions that work well together" in line, so for now (with the current set of supported DCCs) it's definitely the easiest to maintain it like it is now.

**Comment by EricTRocks** [comment]
Auto-registration of plug-ins is a great idea. I created a bit of a lazy plug-in system where again it just looks for the plug-in that passes a test and if it passes, it uses that one. Do you have any experience creating an auto-registering plug-in system? I can see issues where it will try to register a Maya plugin but then errors out because it can't import cmds or pymel when running in stand alone or Softimage.

**Comment by BigRoy** [comment]
> Do you have any experience creating an auto-registering plug-in system?

Not in particular, but it could work roughly similar to Component. Where a plug-in contains code like:

```python
from kraken.core.kraken_system import KrakenSystem
ks = KrakenSystem.getInstance()
ks.registerPlugin(MayaPlugin)
```

> I can see issues where it will try to register a Maya plugin but then errors out because it can't import cmds or pymel when running in stand alone or Softimage.

I guess it's up to the plug-in to have a "register" method that allows to define whether it's a valid plug-in under the condition.

In the example above this could be something like:

```python
MayaPlugin(KrakenPlugin):
    def load(self):
        if not is_maya:
            return False
        else:
            return True
```

This could also just be the `__init__` and raise an error if not valid under the current circumstances:

```python
MayaPlugin(KrakenPlugin):
    def __init__(self):
        if not is_maya:
            raise KrakenPluginLoadError("Not in Maya.")
```

Then the core of the system would try to load registered plug-ins:

```python
loadedPlugins = []
for pluginClass in registeredPlugins():
    try:
        plugin = pluginClass()
    except KrakenPluginLoadError:
        continue
    loadedPlugins.append(plugin)
```

We'd just need to define a minimal Interface that any plug-in would need to implement, like `getClient()` and maybe more?
