### ISSUE TITLE
Component build and eval order

### ISSUE THREAD

**Issue by yamahigashi** [fabric-engine/Kraken#348]
`Edited by EricTRocks for clarity`
Original Title: Constraint.evaluate() results inverted tr when maintainOffset(False)

I pulled the current state of the develop2.x branch and have try to use the new leg + foot components (again).I built the bob, result is a bit odd, 

* L_leg_pelvisInput_cmpIn 's position is very high
* L_arm_root_cmpIn also high (when ikblend 1.0)

  it seems its PoseConstrain offset have extra value by its constrainer's position * 2

in kraken.core.objects.constraints.constraint.py:
``` python
class Constraint(SceneItem):
    ..... snip ....

    def evaluate(self):
        """invokes the constraint causing the output value to be computed.

        Returns:
            bool: True if successful.

        """
        if self.getMaintainOffset() is False:
            def getGlobalXfoFunc(c):
                return c.xfo
            self.getConstrainee().xfo = self.computeOffset(getGlobalXfoFunc=getGlobalXfoFunc)

        return False        
```

I think this should be
``` diff

         if self.getMaintainOffset() is False:
             def getGlobalXfoFunc(c):
                 return c.xfo
-            self.getConstrainee().xfo = self.computeOffset(getGlobalXfoFunc=getGlobalXfoFunc)
+            offsetXfo = self.computeOffset(getGlobalXfoFunc=getGlobalXfoFunc)
+            invVec = Vec3(-1.0, -1.0, -1.0)
+            offsetXfo.tr = offsetXfo.tr * invVec
+            self.getConstrainee().xfo = offsetXfo

         return False
```

is this reasonable?

**Comment by EricTRocks** [comment]
What DCC did you build this in? How did you build the Bob rig? Through the .krg file?

**Comment by yamahigashi** [comment]
sorry i built my custom bob_rig.krg (attached) and, maya2016 and softimage2015
[bob_rig.zip](https://github.com/fabric-engine/Kraken/files/158208/bob_rig.zip)

**Comment by EricTRocks** [comment]
Will look into this shortly. There is another branch that will get merged in tomorrow that changes a few things that affects this. Mainly, input objects no longer are created with maintainOffset = True. Meaning whatever the input object is connected to, it will match it's Xfo without offset.

**Comment by yamahigashi** [comment]
OK, i'm looking forward it! and close this for now. thanks

**Comment by EricTRocks** [comment]
@helgemathee I'm seeing this on develop2.X as well. I don't think the changes that the Oculus folks implemented will address this. Is it possible that the translation is getting doubled up? Will explore over the weekend.

**Comment by mjcg91** [comment]
I had a problem with Input Xfos and offsets recently, which made me change some stuff inside my Components.
The component's objects that were parented to the inputXfo were not generated at their given positions.
While the inputXfo shared the same position as the outputXfo (which was not working before),
sub-objects that relied on the inputXfo had their proper xfo data, but in local space.
Kraken was giving them their proper Xfos, but then, it kind of doubled the parent offset.

It was like the objects were parented to the InputXfo located at the 0,0,0 and once everything was parented, sending the Output onto the inputXfo, which resulted in a double offset.

**Comment by todderasesareddot** [comment]
That's probably because whatever was driving the inputXfo (an outputXfo from another component) was not evaluated properly in the hierarchy build pass.  So, when you got to the constraint pass the inputXfo was still at identity when parenting the children (thus storing an offset).  Then, when the actual DCC nodes are created and evaluated, the inputXfo is evaluated properly and moves to the right location, but it still has the stored erroneous offset from the constraint pass.

Eric and I have chatted about the need to put in checks to make sure certain things happen when a component is built.  It is very easy to end up in situations like this without sanity checks.  I'm more than happy to contribute to this moving forward.

**Comment by EricTRocks** [comment]
Did some digging and the recent changes that were made in the CanvasBuilder branch that were merged in has caused these offsets. This work was needed and is now just showing an area in Kraken we need to refactor. I think what we need to do is to build components based on the connections in the graph. That way we can generate and evaluate the graph in order to ensure that all transforms are in place for the next connected component.

However, this comes to a problematic point when you have a cyclic graph (leg > foot > leg) which is how we have the leg and foot component working right now. For now I'd recommend rolling back to a pre-CanvasBuilder-merge commit until I can figure this out. :)

**Comment by EricTRocks** [comment]
Work has been done on this issue and we've created a new method for creating rigs where it walks the graph to find the correct build order. However we also now don't allow cyclic connections between nodes. I'm going to comment this out and push to develop2.X since it shouldn't have been pushed until discussed and a more fleshed out solution was found.

I'll be looking into walking the full graph instead of just the high level component connections next.

**Comment by helgemathee** [comment]
@EricTRocks: what do you need me to do here? I've sent a pull request for #384, does this also resolve this issue?

**Comment by EricTRocks** [comment]
Nothing, you've done the work. :) Just marked this as an issue you took care of to reference later if needed.
